### ISSUE TITLE
fine-tune bridge centroid set and render to leaflet

### ISSUE THREAD

**Issue by mdlincoln** [dSHARP-CMU/bridgesofPittsburgh#121]
I've exported the estimated centroids for bridges as a set of points with a few attributes for their popups to `osmar/output_data/bridge_centroid_sf.rda`. To-do by @ERSlayton:

1. manually fix centroid locations for complicated/curving bridges in e.g. arcmap (I know that'll mean needing to write out this `sf` object as a shapefile or something - lmk if you prefer I upload it in another fomrat)
2. commit manually-checked point data into repo
3. render onto Leaflet map

since this requires a manual step, we should hold off on finishing it until we are 100% satisfied with the data, pathways, etc.

**Comment by ERSlayton** [comment]
I made the map from the osmar/output_data/bridge_centroid_sf.rda file. Will upload to wordpress shortly. 


![Bridges_ex](https://user-images.githubusercontent.com/37001838/55368790-bdb9c300-54c1-11e9-9083-f5435088a486.png)

**Comment by ERSlayton** [comment]
However, as you said, we may need to manually adjust the frame? How is the progression on this decision making?

**Comment by mdlincoln** [comment]
@ERSlayton are you referring to the full-screen wordpress theme @scottbot is looking for? #112 or something else?
