### ISSUE TITLE
subset edges so they all have at least one terminus inside PGH admin boundary

### ISSUE THREAD

**Issue by mdlincoln** [dSHARP-CMU/bridgesofPittsburgh#34]
Get shapefile and do sp within()

**Comment by mdlincoln** [comment]
This is not as straightforward to do with the base OSM data format as I'd hoped. @ERSlayton would you be able to produce a list of OSM `Node` IDs that fall within the polygon defined by the Pittsburgh administrative boundary?

**Comment by mdlincoln** [comment]
JK @CarolGo did this already, I forgot! using the specified nodes from `Updated_PGH/nodes.csv`

**Comment by mdlincoln** [comment]
It looks like, because the package she was using simplified a lot of the OSM data, I can't just naively subset the graph either to the edges or the nodes in this dataset. However, it may be possible to do a more subtle sub-setting that works at the level of `Ways`, keeping those ways that contain _at least one node_ within the spatially-subsetted data...

**Comment by ERSlayton** [comment]
Hello Matt,

Any chance we could talk about this in person once I get back from DLF? I feel like I might understand what you’re getting at better if I can hear it in person.

Emma
