### ISSUE TITLE
Research ways to turn network back into spatial object programmatically

### ISSUE THREAD

**Issue by mdlincoln** [dSHARP-CMU/bridgesofPittsburgh#65]
@ERSlayton will look into this for R - it may help address #59

**Comment by mdlincoln** [comment]
I've tossed some experiments in with joining coordinates back onto edges and serializing them as WKT that can be VERY quickly plotted by the `sf` package. This handily closes #59

**Comment by ERSlayton** [comment]
I found this link which might be helpful (https://stackoverflow.com/questions/9205227/output-shapefile-for-the-igraph-network-in-r) detailing how to turn an Igrpah into a shapefile, or geographic representation of the map. Excerpt below:
 
You can do this using the sp and maptools packages. There are handy functions writePointsShape() and writeLinesShape() in maptools that will write to the ESRI shapefile format.
Before doing this, it is necessary to extract the lat/lon information from the graph vertices and put it into a SpatialPoints object for the vertices, and a SpatialLinesDataFrame object for the edges.
This code produces a very simple igraph object for the following example:
        library(igraph)
 
        ## Produce a ring graph with 4 vertices
        x <- graph.ring(4)
 
        ## Add lat/lon information to vertices
        V(x)$lat <- c(50, 50, 51, 51)
        V(x)$lon <- c(40, 41, 41, 40)
Now, create the SpatialPoints object for the vertices
        library(sp)
        library(maptools)
 
        ## Create SpatialPoints object containing coordinates
        xV <- SpatialPoints(cbind(V(x)$lon, V(x)$lat))
 
        ## Write vertices to a shapefile
        writePointsShape(xV, fn="vertices")
Finally, create the SpatialLinesDataFrame object for the edges. This is a little messy, but I am yet to find a quick way to produce a SpatialLines object given coordinates.
        ## Create SpatialLinesDataFrame object describing edges
        edges <- get.edgelist(x)+1
        edges <- cbind(edgeNum=1:nrow(edges), v1=edges[,1], v2=edges[,2])
        xE <- apply(edges, 1, function(i) Lines(Line(cbind(c(V(x)$lon[i["v1"]], V(x)$lon[i["v2"]]), c(V(x)$lat[i["v1"]], V(x)$lat[i["v2"]]))), ID=as.character(i["edgeNum"])))
        xE <- SpatialLinesDataFrame(SpatialLines(xE), data=data.frame(edgeNum=1:nrow(edges)))
 
        ## Write edges to a shapefile
        writeLinesShape(xE, fn="edges")

**Comment by ERSlayton** [comment]
Thanks for looking into it @mdlincoln. I am glad to hear it is in line with what you have made. I will make sure to target my search more towards sf now. 

I am reading through the blog post you suggested now, to help target my search.

**Comment by mdlincoln** [comment]
Also see #73

**Comment by mdlincoln** [comment]
Looks like we have a pretty clear path forward on this, so closing in favor of specific task tickets like #73 and #79
