### ISSUE TITLE
Update Leaflet map for website

### ISSUE THREAD

**Issue by ERSlayton** [dSHARP-CMU/bridgesofPittsburgh#79]
Update leaflet map for eventual use during OSM workshop and on website.

Must include:

Access to attribute list
Access to list of URL's taking you to open street map
Includes a way to view progression of route segments

**Comment by ERSlayton** [comment]
Update leaflet map for eventual use during OSM workshop and on website. 

Must include:
- Access to attribute list 
- Access to list of URL's taking you to open street map 
- Includes a way to view progression of route segments

**Comment by mdlincoln** [comment]
library that may help us display overlapping pathways by doing a slight offset a-la a metro map: https://github.com/bbecquet/Leaflet.PolylineOffset

**Comment by mdlincoln** [comment]
Gonna close this in favor of more granular tasks
