### ISSUE TITLE
Add Matt's bio to the website

### ISSUE THREAD

**Issue by jmotis** [dSHARP-CMU/bridgesofPittsburgh#83]
Hey Matt, I just was looking at the website while updating my CV and realized we don't have your bio up there yet! If you send me a bio and a headshot at your convenience, I can add it for you.

**Comment by mdlincoln** [comment]
>Dr. Matthew Lincoln is the Digital Humanities Developer at dSHARP, the digital scholarship center at Carnegie Mellon University, where he focuses on computational and data-driven approaches to the study of history and culture. He earned his PhD in Art History at the University of Maryland, College Park, and has held positions at the Getty Research Institute and the National Gallery of Art. He is an editorial board member of _The Programming Historian_ and is currently working on a book project co-authored with Dr. Sandra van Ginhoven, to mine the Getty Provenance Index Databases for insights into the history of collecting and the art market.

![getty_cropped](https://user-images.githubusercontent.com/4392604/49737626-54384f00-fc5b-11e8-90c1-39ef0006dc73.jpeg)
